#!/bin/bash

if [[ $# -ge 1 && "$1" == "u" ]]
then
    echo "Uninstalling udunitspy"
    pip uninstall -y numexpr pytest py pytest-cov udunitspy
    clean
elif [[ $# -ge 1 && "$1" == "d" ]]
then
    python setup.py sdist
else
    python setup.py develop
fi